//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

pub use super::customers::Entity as Customers;
pub use super::service_list::Entity as ServiceList;
pub use super::service_order_items::Entity as ServiceOrderItems;
pub use super::service_orders::Entity as ServiceOrders;
pub use super::spareparts::Entity as Spareparts;
pub use super::users::Entity as Users;
pub use super::vehicles::Entity as Vehicles;
