//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "service_order_items")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub service_order_id: i32,
    pub sparepart_id: i32,
    pub quantity: i32,
    pub price_at_time: i64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::service_orders::Entity",
        from = "Column::ServiceOrderId",
        to = "super::service_orders::Column::Id",
        on_update = "Restrict",
        on_delete = "Cascade"
    )]
    ServiceOrders,
    #[sea_orm(
        belongs_to = "super::spareparts::Entity",
        from = "Column::SparepartId",
        to = "super::spareparts::Column::Id",
        on_update = "Restrict",
        on_delete = "Restrict"
    )]
    Spareparts,
}

impl Related<super::service_orders::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ServiceOrders.def()
    }
}

impl Related<super::spareparts::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Spareparts.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
