//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "service_orders")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub vehicle_id: i32,
    pub mechanic_id: i32,
    pub front_desk_id: i32,
    pub status: String,
    pub total_price: i64,
    pub created_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::service_order_items::Entity")]
    ServiceOrderItems,
    #[sea_orm(
        belongs_to = "super::users::Entity",
        from = "Column::MechanicId",
        to = "super::users::Column::Id",
        on_update = "Restrict",
        on_delete = "Restrict"
    )]
    Users,
    #[sea_orm(
        belongs_to = "super::vehicles::Entity",
        from = "Column::VehicleId",
        to = "super::vehicles::Column::Id",
        on_update = "Restrict",
        on_delete = "Restrict"
    )]
    Vehicles,
}

impl Related<super::service_order_items::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ServiceOrderItems.def()
    }
}

impl Related<super::users::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Users.def()
    }
}

impl Related<super::vehicles::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Vehicles.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
