//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "users")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    #[sea_orm(unique)]
    pub username: String,
    pub password: String,
    pub fullname: String,
    pub role: String,
    pub refresh_token: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::service_orders::Entity")]
    ServiceOrders,
}

impl Related<super::service_orders::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ServiceOrders.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
