//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "vehicles")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub customer_id: i32,
    #[sea_orm(unique)]
    pub plate_number: String,
    pub brand: String,
    pub model: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::customers::Entity",
        from = "Column::CustomerId",
        to = "super::customers::Column::Id",
        on_update = "Restrict",
        on_delete = "Cascade"
    )]
    Customers,
    #[sea_orm(has_many = "super::service_orders::Entity")]
    ServiceOrders,
}

impl Related<super::customers::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Customers.def()
    }
}

impl Related<super::service_orders::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ServiceOrders.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
